kind: pipeline
name: python-tests
type: docker

steps:
  - name: static-analysis
    image: python
    commands:
      - python -V
      - python3 -m pip install flake8
      - python3 -m flake8 src/python-movie-collection-checker/*.py

  - name: build-image
    image: docker
    commands:
      - docker build -t "python-movie-collection-checker:0.0.1" .
